function renderPlanning(){const list=monthMaterials(),peak=weekBuckets(list).reduce((a,x)=>x.count>a.count?x:a,{label:"—",count:0});document.getElementById("planStatTotal").textContent=list.length;document.getElementById("planStatUrgent").textContent=list.filter(isUrgent).length;document.getElementById("planStatRecurring").textContent=list.filter(x=>x.recurrence!=="Sob demanda").length;document.getElementById("planStatPeak").textContent=peak.count?`${peak.label} · ${peak.count}`:"—";
document.getElementById("planningList").innerHTML=list.length?list.map(m=>`<div class="plan-item"><div class="plan-top"><div><div class="plan-title">${esc(m.name)}</div><div class="plan-meta">${fullDate(m.date)} · ${natureIcon(m.nature)} ${esc(m.nature)} · ${recurrenceIcon(m.recurrence)} ${esc(m.recurrence)}</div></div><div class="plan-actions"><span class="status ${statusClass(m.status)}">${esc(m.status)}</span><button class="btn btn-secondary" style="padding:8px 11px" onclick="openMaterial(${m.id})">Abrir</button></div></div><div class="milestone-row">${getMilestones(m.date,m.requiresValidation).map(ms=>`<div class="milestone"><strong>${ms.key} · ${ms.label}</strong><span>${fullDate(ms.date)}</span></div>`).join("")}</div></div>`).join(""):'<div class="empty">Nenhum item neste mês.</div>';
const summary=[["Total de itens",list.length],["Importantes e urgentes",list.filter(isUrgent).length],["Recorrentes",list.filter(x=>x.recurrence!=="Sob demanda").length],["Sob demanda",list.filter(x=>x.recurrence==="Sob demanda").length],["Aguardando Adriana",list.filter(x=>x.requiresValidation&&x.status==="Validação").length],["Semana mais carregada",peak.count?`${peak.label} (${peak.count})`:"—"]];document.getElementById("meetingSummary").innerHTML=summary.map(x=>`<div class="summary-line"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");
const p=[...list].sort((a,b)=>(Number(isUrgent(b))-Number(isUrgent(a)))||a.date.localeCompare(b.date)).slice(0,4);document.getElementById("priorityList").innerHTML=p.length?p.map(m=>`<div class="priority-item"><div><strong>${esc(m.name)}</strong><div class="muted-text">${fullDate(m.date)} · ${isUrgent(m)?"urgente":"planejável"}</div></div><span class="status ${statusClass(m.status)}">${esc(m.status)}</span></div>`).join(""):'<div class="empty">Sem prioridades.</div>';
const cross=materials.filter(m=>{if(sameMonth(m.date,currentMonth.year,currentMonth.month))return false;const d7=getMilestones(m.date,m.requiresValidation)[0].date;return sameMonth(d7,currentMonth.year,currentMonth.month)}).sort((a,b)=>getMilestones(a.date,a.requiresValidation)[0].date.localeCompare(getMilestones(b.date,b.requiresValidation)[0].date));document.getElementById("crossMonthPrep").innerHTML=cross.length?cross.map(m=>`<div class="priority-item"><div><strong>${esc(m.name)}</strong><div class="muted-text">Início ${fullDate(getMilestones(m.date,m.requiresValidation)[0].date)} · entrega ${fullDate(m.date)}</div></div><span class="badge badge-purple">D-7</span></div>`).join(""):'<div class="empty" style="padding:10px">Nenhuma preparação atravessando o mês.</div>'}
function renderActivity(){const lastSeen=localStorage.getItem(`cm_last_seen_${activeUser}`)||"",unread=activities.filter(a=>a.usuario!==activeUser&&(!lastSeen||a.created_at>lastSeen)).length;const count=document.getElementById("bellCount");count.textContent=unread;count.classList.toggle("hidden",unread===0);document.getElementById("activityList").innerHTML=activities.length?activities.map(a=>{const isUnread=a.usuario!==activeUser&&(!lastSeen||a.created_at>lastSeen);return`<div class="activity-item ${isUnread?"unread":""}"><strong>${esc(a.usuario)} · ${esc(a.acao)}</strong><p>${esc(a.detalhe||"")}</p><div class="activity-time">${formatActivityDate(a.created_at)}</div></div>`}).join(""):'<div class="empty">Ainda não há atividades registradas.</div>'}
function renderAll(){renderUser();renderMonthChrome();renderKPIs();renderHome();renderCapacity();renderCalendar();renderDirector();renderPlanning();renderActivity()}
async function changeMonth(delta){const d=new Date(currentMonth.year,currentMonth.month+delta,1);currentMonth={year:d.getFullYear(),month:d.getMonth()};await ensureRecurringForMonth(currentMonth.year,currentMonth.month);renderAll()}
async function toggleActivity(){const p=document.getElementById("activityPanel"),opening=!p.classList.contains("show");p.classList.toggle("show");if(opening){localStorage.setItem(`cm_last_seen_${activeUser}`,new Date().toISOString());await loadActivities();renderActivity()}}
async function openMaterial(id){const m=materials.find(x=>x.id===id);if(!m)return;if(activeUser&&!viewedThisSession.has(`${activeUser}:${id}`)){viewedThisSession.add(`${activeUser}:${id}`);await logActivity("Visualizou material",id,m.name);await loadActivities()}editMaterial(id)}
function updateValidationField(){const req=document.getElementById("fRequiresValidation").value==="true";const v=document.getElementById("fValidator");v.value=req?"Adriana":"Não se aplica";v.style.opacity=req?"1":".55";renderAutoMilestonesPreview()}
function renderAutoMilestonesPreview(){const date=document.getElementById("fDate").value,target=document.getElementById("modalMilestones"),req=document.getElementById("fRequiresValidation").value==="true";target.innerHTML=date?getMilestones(date,req).map(ms=>`<div class="milestone"><strong>${ms.key} · ${ms.label}</strong><span>${fullDate(ms.date)}</span></div>`).join(""):'<div class="muted-text">Selecione a data.</div>'}
async function renderItemHistory(id){const {data}=await sb.from("controle_materiais_atividade").select("*").eq("material_id",id).order("created_at",{ascending:false}).limit(12);document.getElementById("historyBox").classList.remove("hidden");document.getElementById("historyList").innerHTML=(data||[]).length?(data||[]).map(a=>`<div class="history-line"><strong>${esc(a.usuario)}</strong> · ${esc(a.acao)} · ${formatActivityDate(a.created_at)}</div>`).join(""):'<div class="muted-text">Sem histórico.</div>'}
function applyKnownDefaults(name){const n=name.toLowerCase();if(n.includes("acelera"))return["Importante / não urgente","Rito","Semanal",false];if(n.includes("conexão")||n.includes("conexao"))return["Importante / não urgente","Rito","Mensal",true];if(n.includes("plano comercial"))return["Importante / não urgente","Material","Mensal",false];if(n.includes("radar")||n.includes("1:1")||n.includes("sync")||n.includes("fórum")||n.includes("forum"))return["Importante e urgente","Rito","Sob demanda",true];return["Importante e urgente","Demanda extraordinária","Sob demanda",true]}
