-- Controle de Materiais V3.8
-- SQL de reconstrução do banco.
-- Revisar antes de executar em um ambiente que já possua dados.

create table if not exists public.controle_materiais (
  id bigint generated by default as identity primary key,
  nome text not null,
  data_rito date not null,
  status text not null default 'Planejado'
    check (status in ('Planejado','Em produção','Validação','Finalizado')),
  responsavel text not null default 'Walisom',
  validador text not null default 'Diretora',
  link_sharepoint text,
  observacao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  prioridade text not null default 'Importante / não urgente',
  natureza text not null default 'Rito',
  recorrencia text not null default 'Sob demanda',
  origem_recorrencia text unique,
  criado_por text not null default 'Walisom',
  requer_validacao boolean not null default true
);

create table if not exists public.controle_materiais_atividade (
  id bigint generated by default as identity primary key,
  material_id bigint,
  usuario text not null,
  acao text not null,
  detalhe text,
  created_at timestamptz not null default now()
);

alter table public.controle_materiais_atividade
  drop constraint if exists controle_materiais_atividade_material_id_fkey;

alter table public.controle_materiais_atividade
  add constraint controle_materiais_atividade_material_id_fkey
  foreign key (material_id)
  references public.controle_materiais(id)
  on delete set null;

create table if not exists public.controle_materiais_recorrencia_excecoes (
  id bigint generated by default as identity primary key,
  origem_recorrencia text not null unique,
  nome text,
  data_rito date,
  excluido_por text not null,
  created_at timestamptz not null default now()
);

alter table public.controle_materiais enable row level security;
alter table public.controle_materiais_atividade enable row level security;
alter table public.controle_materiais_recorrencia_excecoes enable row level security;

drop policy if exists controle_materiais_select on public.controle_materiais;
create policy controle_materiais_select on public.controle_materiais
for select to anon, authenticated using (true);

drop policy if exists controle_materiais_insert on public.controle_materiais;
create policy controle_materiais_insert on public.controle_materiais
for insert to anon, authenticated with check (true);

drop policy if exists controle_materiais_update on public.controle_materiais;
create policy controle_materiais_update on public.controle_materiais
for update to anon, authenticated using (true) with check (true);

drop policy if exists controle_materiais_delete on public.controle_materiais;
create policy controle_materiais_delete on public.controle_materiais
for delete to anon, authenticated using (true);

drop policy if exists controle_materiais_atividade_select on public.controle_materiais_atividade;
create policy controle_materiais_atividade_select on public.controle_materiais_atividade
for select to anon, authenticated using (true);

drop policy if exists controle_materiais_atividade_insert on public.controle_materiais_atividade;
create policy controle_materiais_atividade_insert on public.controle_materiais_atividade
for insert to anon, authenticated with check (true);

drop policy if exists rec_excecoes_select on public.controle_materiais_recorrencia_excecoes;
create policy rec_excecoes_select on public.controle_materiais_recorrencia_excecoes
for select to anon, authenticated using (true);

drop policy if exists rec_excecoes_insert on public.controle_materiais_recorrencia_excecoes;
create policy rec_excecoes_insert on public.controle_materiais_recorrencia_excecoes
for insert to anon, authenticated with check (true);

drop policy if exists rec_excecoes_delete on public.controle_materiais_recorrencia_excecoes;
create policy rec_excecoes_delete on public.controle_materiais_recorrencia_excecoes
for delete to anon, authenticated using (true);

create or replace function public.excluir_material(
  p_id bigint,
  p_modo text,
  p_usuario text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.controle_materiais%rowtype;
  v_proximo public.controle_materiais%rowtype;
  v_root bigint;
  v_novo_root bigint;
  v_prefixo_antigo text;
  v_prefixo_novo text;
  v_prefixo_legado text;
  v_proxima_data date;
  v_inicio_mes date;
  v_fim_mes date;
  v_dia integer;
  v_count integer := 0;
  v_acao text;
begin
  select * into v_item from public.controle_materiais where id = p_id;
  if not found then raise exception 'Material não encontrado.'; end if;
  if p_modo not in ('item','tudo') then raise exception 'Modo de exclusão inválido.'; end if;

  if p_modo = 'tudo' then
    if v_item.recorrencia = 'Sob demanda' then
      delete from public.controle_materiais where id = v_item.id;
      get diagnostics v_count = row_count;
    elsif v_item.origem_recorrencia ~ '^series:[0-9]+:' then
      v_root := split_part(v_item.origem_recorrencia, ':', 2)::bigint;
      v_prefixo_antigo := 'series:' || v_root || ':';
      delete from public.controle_materiais_recorrencia_excecoes where origem_recorrencia like v_prefixo_antigo || '%';
      delete from public.controle_materiais where id = v_root or origem_recorrencia like v_prefixo_antigo || '%';
      get diagnostics v_count = row_count;
    elsif v_item.origem_recorrencia is null then
      v_root := v_item.id;
      v_prefixo_antigo := 'series:' || v_root || ':';
      delete from public.controle_materiais_recorrencia_excecoes where origem_recorrencia like v_prefixo_antigo || '%';
      delete from public.controle_materiais where id = v_root or origem_recorrencia like v_prefixo_antigo || '%';
      get diagnostics v_count = row_count;
    else
      v_prefixo_legado := split_part(v_item.origem_recorrencia, ':', 1) || ':';
      delete from public.controle_materiais_recorrencia_excecoes
      where origem_recorrencia like v_prefixo_legado || '%' and (nome = v_item.nome or nome is null);
      delete from public.controle_materiais
      where nome = v_item.nome and recorrencia = v_item.recorrencia
        and (id = v_item.id or origem_recorrencia like v_prefixo_legado || '%');
      get diagnostics v_count = row_count;
    end if;

    v_acao := case when v_item.recorrencia = 'Sob demanda' then 'Excluiu agenda' else 'Excluiu série recorrente' end;

    insert into public.controle_materiais_atividade(material_id, usuario, acao, detalhe)
    values (
      null,
      coalesce(nullif(p_usuario,''),'Sistema'),
      v_acao,
      v_item.nome || ' · ' || to_char(v_item.data_rito,'DD/MM/YYYY') ||
      case when v_item.recorrencia <> 'Sob demanda' then ' · ' || v_count || ' ocorrência(s)' else '' end
    );

    return jsonb_build_object('success', true, 'mode', 'tudo', 'deleted', v_count);
  end if;

  if v_item.recorrencia = 'Sob demanda' then
    delete from public.controle_materiais where id = v_item.id;
    v_count := 1;

  elsif v_item.origem_recorrencia ~ '^series:[0-9]+:' then
    insert into public.controle_materiais_recorrencia_excecoes
      (origem_recorrencia, nome, data_rito, excluido_por)
    values
      (v_item.origem_recorrencia, v_item.nome, v_item.data_rito, coalesce(nullif(p_usuario,''),'Sistema'))
    on conflict (origem_recorrencia)
    do update set nome = excluded.nome, data_rito = excluded.data_rito, excluido_por = excluded.excluido_por;

    delete from public.controle_materiais where id = v_item.id;
    v_count := 1;

  elsif v_item.origem_recorrencia is not null then
    insert into public.controle_materiais_recorrencia_excecoes
      (origem_recorrencia, nome, data_rito, excluido_por)
    values
      (v_item.origem_recorrencia, v_item.nome, v_item.data_rito, coalesce(nullif(p_usuario,''),'Sistema'))
    on conflict (origem_recorrencia)
    do update set nome = excluded.nome, data_rito = excluded.data_rito, excluido_por = excluded.excluido_por;

    delete from public.controle_materiais where id = v_item.id;
    v_count := 1;

  else
    v_root := v_item.id;
    v_prefixo_antigo := 'series:' || v_root || ':';

    select * into v_proximo
    from public.controle_materiais
    where origem_recorrencia like v_prefixo_antigo || '%'
      and data_rito > v_item.data_rito
    order by data_rito, id
    limit 1;

    if found then
      update public.controle_materiais
      set origem_recorrencia = null,
          criado_por = coalesce(v_item.criado_por, criado_por)
      where id = v_proximo.id
      returning id into v_novo_root;
    else
      if v_item.recorrencia = 'Semanal' then
        v_proxima_data := v_item.data_rito + 7;
      elsif v_item.recorrencia = 'Quinzenal' then
        v_proxima_data := v_item.data_rito + 14;
      elsif v_item.recorrencia = 'Mensal' then
        v_inicio_mes := date_trunc('month', v_item.data_rito + interval '1 month')::date;
        v_fim_mes := (v_inicio_mes + interval '1 month - 1 day')::date;
        v_dia := least(extract(day from v_item.data_rito)::integer, extract(day from v_fim_mes)::integer);
        v_proxima_data := v_inicio_mes + (v_dia - 1);
      else
        v_proxima_data := v_item.data_rito + 7;
      end if;

      insert into public.controle_materiais(
        nome, data_rito, status, responsavel, validador,
        link_sharepoint, observacao, prioridade, natureza,
        recorrencia, origem_recorrencia, criado_por, requer_validacao
      )
      values(
        v_item.nome, v_proxima_data, 'Planejado', v_item.responsavel, v_item.validador,
        v_item.link_sharepoint, v_item.observacao, v_item.prioridade, v_item.natureza,
        v_item.recorrencia, null, v_item.criado_por, v_item.requer_validacao
      )
      returning id into v_novo_root;
    end if;

    v_prefixo_novo := 'series:' || v_novo_root || ':';

    update public.controle_materiais
    set origem_recorrencia = replace(origem_recorrencia, v_prefixo_antigo, v_prefixo_novo)
    where origem_recorrencia like v_prefixo_antigo || '%';

    update public.controle_materiais_recorrencia_excecoes
    set origem_recorrencia = replace(origem_recorrencia, v_prefixo_antigo, v_prefixo_novo)
    where origem_recorrencia like v_prefixo_antigo || '%';

    delete from public.controle_materiais where id = v_item.id;
    v_count := 1;
  end if;

  insert into public.controle_materiais_atividade(material_id, usuario, acao, detalhe)
  values (
    null,
    coalesce(nullif(p_usuario,''),'Sistema'),
    'Excluiu ocorrência',
    v_item.nome || ' · ' || to_char(v_item.data_rito,'DD/MM/YYYY')
  );

  return jsonb_build_object('success', true, 'mode', 'item', 'deleted', v_count, 'new_master_id', v_novo_root);
end;
$$;

revoke all on function public.excluir_material(bigint,text,text) from public;
grant execute on function public.excluir_material(bigint,text,text) to anon, authenticated;

-- Realtime
-- O frontend da V3.8 possui subscriptions, porém o snapshot verificado em
-- 08/10/2026 não tinha tabelas públicas registradas em supabase_realtime.
-- Se sincronização instantânea for requisito, habilite explicitamente:
--
-- alter publication supabase_realtime add table public.controle_materiais;
-- alter publication supabase_realtime add table public.controle_materiais_atividade;
